// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Parser (
        ap_ready,
        packet_in_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3
);


output   ap_ready;
input  [255:0] packet_in_V_read;
output  [47:0] ap_return_0;
output  [47:0] ap_return_1;
output  [15:0] ap_return_2;
output  [2:0] ap_return_3;

wire   [15:0] p_Result_2_fu_54_p4;
wire   [0:0] cond_fu_64_p2;
wire   [47:0] tmp_fu_40_p1;
wire   [2:0] state_write_assign_c_fu_70_p3;

assign ap_ready = 1'b1;

assign ap_return_0 = tmp_fu_40_p1;

assign ap_return_1 = {{packet_in_V_read[95:48]}};

assign ap_return_2 = {{packet_in_V_read[111:96]}};

assign ap_return_3 = state_write_assign_c_fu_70_p3;

assign cond_fu_64_p2 = ((p_Result_2_fu_54_p4 == 16'd2048) ? 1'b1 : 1'b0);

assign p_Result_2_fu_54_p4 = {{packet_in_V_read[111:96]}};

assign state_write_assign_c_fu_70_p3 = ((cond_fu_64_p2[0:0] === 1'b1) ? 3'd2 : 3'd3);

assign tmp_fu_40_p1 = packet_in_V_read[47:0];

endmodule //Parser
