// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Parser (
        ap_ready,
        packet_in_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [255:0] packet_in_V_read;
output  [47:0] ap_return_0;
output  [47:0] ap_return_1;
output  [15:0] ap_return_2;

wire   [47:0] tmp_fu_34_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = tmp_fu_34_p1;

assign ap_return_1 = {{packet_in_V_read[95:48]}};

assign ap_return_2 = {{packet_in_V_read[111:96]}};

assign tmp_fu_34_p1 = packet_in_V_read[47:0];

endmodule //Parser
