// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Deparser (
        ap_ready,
        packet_in_V_read,
        p_ethernet_dstAddr_V,
        p_ethernet_srcAddr_V,
        p_ethernet_etherType,
        ap_return
);


output   ap_ready;
input  [255:0] packet_in_V_read;
input  [47:0] p_ethernet_dstAddr_V;
input  [47:0] p_ethernet_srcAddr_V;
input  [15:0] p_ethernet_etherType;
output  [255:0] ap_return;

wire   [111:0] tmp_1_fu_54_p4;

assign ap_ready = 1'b1;

assign ap_return = {{packet_in_V_read[255:112]}, {tmp_1_fu_54_p4}};

assign tmp_1_fu_54_p4 = {{{p_ethernet_etherType}, {p_ethernet_srcAddr_V}}, {p_ethernet_dstAddr_V}};

endmodule //Deparser
