// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Pipeline (
        ap_ready,
        state_read,
        parsed_packet_ethern,
        in_sume_metadata_VAL,
        in_sume_metadata_V_r,
        out_sume_metadata_VA,
        out_sume_metadata_VA_ap_vld,
        out_sume_metadata_V,
        out_sume_metadata_V_ap_vld
);


output   ap_ready;
input  [2:0] state_read;
input  [47:0] parsed_packet_ethern;
input  [0:0] in_sume_metadata_VAL;
input  [127:0] in_sume_metadata_V_r;
output  [0:0] out_sume_metadata_VA;
output   out_sume_metadata_VA_ap_vld;
output  [127:0] out_sume_metadata_V;
output   out_sume_metadata_V_ap_vld;

reg out_sume_metadata_VA_ap_vld;
reg out_sume_metadata_V_ap_vld;

wire   [0:0] tmp_4_fu_101_p2;
wire   [0:0] tmp_i_fu_107_p2;
wire   [0:0] tmp_1_i_fu_113_p2;
wire   [0:0] sel_tmp1_fu_131_p2;
wire   [0:0] sel_tmp6_demorgan_fu_143_p2;
wire   [0:0] tmp_2_i_fu_119_p2;
wire   [0:0] sel_tmp6_fu_149_p2;
wire   [0:0] sel_tmp7_fu_155_p2;
wire   [0:0] sel_tmp2_fu_137_p2;
wire   [0:0] tmp_3_i_fu_125_p2;
wire   [0:0] or_cond_fu_169_p2;
wire   [6:0] newSel_cast_cast_fu_161_p3;
wire   [6:0] newSel9_fu_175_p3;
wire   [0:0] or_cond1_fu_183_p2;
wire   [0:0] or_cond2_fu_197_p2;
wire   [6:0] newSel_fu_189_p3;
wire   [6:0] dst_port_V_fu_203_p3;
wire   [7:0] newSel13_cast_fu_211_p1;

always @ (*) begin
    if ((tmp_4_fu_101_p2 == 1'd1)) begin
        out_sume_metadata_VA_ap_vld = 1'b1;
    end else begin
        out_sume_metadata_VA_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_4_fu_101_p2 == 1'd1)) begin
        out_sume_metadata_V_ap_vld = 1'b1;
    end else begin
        out_sume_metadata_V_ap_vld = 1'b0;
    end
end

assign ap_ready = 1'b1;

assign dst_port_V_fu_203_p3 = ((or_cond2_fu_197_p2[0:0] === 1'b1) ? newSel_fu_189_p3 : 7'd0);

assign newSel13_cast_fu_211_p1 = dst_port_V_fu_203_p3;

assign newSel9_fu_175_p3 = ((tmp_i_fu_107_p2[0:0] === 1'b1) ? 7'd1 : 7'd64);

assign newSel_cast_cast_fu_161_p3 = ((sel_tmp7_fu_155_p2[0:0] === 1'b1) ? 7'd16 : 7'd4);

assign newSel_fu_189_p3 = ((or_cond_fu_169_p2[0:0] === 1'b1) ? newSel_cast_cast_fu_161_p3 : newSel9_fu_175_p3);

assign or_cond1_fu_183_p2 = (tmp_i_fu_107_p2 | tmp_3_i_fu_125_p2);

assign or_cond2_fu_197_p2 = (or_cond_fu_169_p2 | or_cond1_fu_183_p2);

assign or_cond_fu_169_p2 = (sel_tmp7_fu_155_p2 | sel_tmp2_fu_137_p2);

assign out_sume_metadata_V = {{in_sume_metadata_V_r[127:32]}, {newSel13_cast_fu_211_p1}, {in_sume_metadata_V_r[23:0]}};

assign out_sume_metadata_VA = in_sume_metadata_VAL;

assign sel_tmp1_fu_131_p2 = (tmp_i_fu_107_p2 ^ 1'd1);

assign sel_tmp2_fu_137_p2 = (tmp_1_i_fu_113_p2 & sel_tmp1_fu_131_p2);

assign sel_tmp6_demorgan_fu_143_p2 = (tmp_i_fu_107_p2 | tmp_1_i_fu_113_p2);

assign sel_tmp6_fu_149_p2 = (sel_tmp6_demorgan_fu_143_p2 ^ 1'd1);

assign sel_tmp7_fu_155_p2 = (tmp_2_i_fu_119_p2 & sel_tmp6_fu_149_p2);

assign tmp_1_i_fu_113_p2 = ((parsed_packet_ethern == 48'd8942694572552) ? 1'b1 : 1'b0);

assign tmp_2_i_fu_119_p2 = ((parsed_packet_ethern == 48'd9015995347720) ? 1'b1 : 1'b0);

assign tmp_3_i_fu_125_p2 = ((parsed_packet_ethern == 48'd9089296122888) ? 1'b1 : 1'b0);

assign tmp_4_fu_101_p2 = ((state_read == 3'd2) ? 1'b1 : 1'b0);

assign tmp_i_fu_107_p2 = ((parsed_packet_ethern == 48'd8869393797384) ? 1'b1 : 1'b0);

endmodule //Pipeline
