// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="SimpleSumeSwitchCpp,hls_ip_2018_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx690tffg1761-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.609400,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=45,HLS_SYN_LUT=251,HLS_VERSION=2018_2}" *)

module SimpleSumeSwitchCpp (
        in_TDATA_V,
        in_TKEEP_V,
        in_TLAST_V,
        in_TVALID_V,
        in_TREADY_V,
        out_TDATA_V,
        out_TKEEP_V,
        out_TLAST_V,
        out_TVALID_V,
        out_TREADY_V,
        enable_processing_V,
        tuple_in_sume_metadata_VALID_V,
        tuple_in_sume_metadata_DATA_V,
        tuple_out_sume_metadata_VALID_V,
        tuple_out_sume_metadata_DATA_V,
        tuple_out_digest_data_VALID_V,
        tuple_out_digest_data_DATA_V,
        clk_lookup_V,
        clk_lookup_rst_V,
        internal_rst_done_V,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        clk_control,
        ap_rst_n_clk_control
);

parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input  [255:0] in_TDATA_V;
input  [31:0] in_TKEEP_V;
input  [0:0] in_TLAST_V;
input  [0:0] in_TVALID_V;
output  [0:0] in_TREADY_V;
output  [255:0] out_TDATA_V;
output  [31:0] out_TKEEP_V;
output  [0:0] out_TLAST_V;
output  [0:0] out_TVALID_V;
input  [0:0] out_TREADY_V;
input  [0:0] enable_processing_V;
input  [0:0] tuple_in_sume_metadata_VALID_V;
input  [127:0] tuple_in_sume_metadata_DATA_V;
output  [0:0] tuple_out_sume_metadata_VALID_V;
output  [127:0] tuple_out_sume_metadata_DATA_V;
output  [0:0] tuple_out_digest_data_VALID_V;
output  [255:0] tuple_out_digest_data_DATA_V;
input  [0:0] clk_lookup_V;
input  [0:0] clk_lookup_rst_V;
output  [0:0] internal_rst_done_V;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
input   clk_control;
input   ap_rst_n_clk_control;

reg[0:0] out_TVALID_V;

wire   [8:0] control_S_AXI_AWADDR_V;
 reg    ap_rst_n_inv;
reg    ap_rst_n_clk_control_inv;
wire    StgValue_57_Pipeline_fu_208_ap_ready;
wire   [0:0] StgValue_57_Pipeline_fu_208_out_sume_metadata_vl;
wire    StgValue_57_Pipeline_fu_208_out_sume_metadata_vl_ap_vld;
wire   [127:0] StgValue_57_Pipeline_fu_208_out_sume_metadata_V;
wire    StgValue_57_Pipeline_fu_208_out_sume_metadata_V_ap_vld;
wire    Parser_ret_Parser_fu_222_ap_ready;
wire   [47:0] Parser_ret_Parser_fu_222_ap_return_0;
wire   [47:0] Parser_ret_Parser_fu_222_ap_return_1;
wire   [15:0] Parser_ret_Parser_fu_222_ap_return_2;
wire   [2:0] Parser_ret_Parser_fu_222_ap_return_3;
wire    call_ret_Deparser_fu_228_ap_ready;
wire   [255:0] call_ret_Deparser_fu_228_ap_return;
reg   [0:0] ap_phi_mux_storemerge_phi_fu_196_p6;
wire   [0:0] in_TVALID_V_read_read_fu_116_p2;
wire   [0:0] out_TREADY_V_read_read_fu_173_p2;

SimpleSumeSwitchCpp_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
SimpleSumeSwitchCpp_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(clk_control),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .control_S_AXI_AWADDR_V(control_S_AXI_AWADDR_V),
    .clk(ap_clk),
    .rst(ap_rst_n_clk_control_inv)
);

Pipeline StgValue_57_Pipeline_fu_208(
    .ap_ready(StgValue_57_Pipeline_fu_208_ap_ready),
    .state_read(Parser_ret_Parser_fu_222_ap_return_3),
    .p_ethernet_dstAddr_V(Parser_ret_Parser_fu_222_ap_return_0),
    .in_sume_metadata_vld(tuple_in_sume_metadata_VALID_V),
    .in_sume_metadata_V_r(tuple_in_sume_metadata_DATA_V),
    .out_sume_metadata_vl(StgValue_57_Pipeline_fu_208_out_sume_metadata_vl),
    .out_sume_metadata_vl_ap_vld(StgValue_57_Pipeline_fu_208_out_sume_metadata_vl_ap_vld),
    .out_sume_metadata_V(StgValue_57_Pipeline_fu_208_out_sume_metadata_V),
    .out_sume_metadata_V_ap_vld(StgValue_57_Pipeline_fu_208_out_sume_metadata_V_ap_vld)
);

Parser Parser_ret_Parser_fu_222(
    .ap_ready(Parser_ret_Parser_fu_222_ap_ready),
    .packet_in_V_read(in_TDATA_V),
    .ap_return_0(Parser_ret_Parser_fu_222_ap_return_0),
    .ap_return_1(Parser_ret_Parser_fu_222_ap_return_1),
    .ap_return_2(Parser_ret_Parser_fu_222_ap_return_2),
    .ap_return_3(Parser_ret_Parser_fu_222_ap_return_3)
);

Deparser call_ret_Deparser_fu_228(
    .ap_ready(call_ret_Deparser_fu_228_ap_ready),
    .packet_in_V_read(in_TDATA_V),
    .p_ethernet_dstAddr_V(Parser_ret_Parser_fu_222_ap_return_0),
    .p_ethernet_srcAddr_V(Parser_ret_Parser_fu_222_ap_return_1),
    .p_ethernet_etherType(Parser_ret_Parser_fu_222_ap_return_2),
    .ap_return(call_ret_Deparser_fu_228_ap_return)
);

always @ (*) begin
    if (((out_TREADY_V_read_read_fu_173_p2 == 1'd0) & (in_TVALID_V_read_read_fu_116_p2 == 1'd1))) begin
        ap_phi_mux_storemerge_phi_fu_196_p6 = 1'd0;
    end else if (((in_TVALID_V_read_read_fu_116_p2 == 1'd0) | ((in_TVALID_V_read_read_fu_116_p2 == 1'd1) & (out_TREADY_V_read_read_fu_173_p2 == 1'd1)))) begin
        ap_phi_mux_storemerge_phi_fu_196_p6 = 1'd1;
    end else begin
        ap_phi_mux_storemerge_phi_fu_196_p6 = 'bx;
    end
end

always @ (*) begin
    if ((in_TVALID_V_read_read_fu_116_p2 == 1'd1)) begin
        out_TVALID_V = 1'd1;
    end else if ((in_TVALID_V_read_read_fu_116_p2 == 1'd0)) begin
        out_TVALID_V = 1'd0;
    end else begin
        out_TVALID_V = 'bx;
    end
end

always @ (*) begin
    ap_rst_n_clk_control_inv = ~ap_rst_n_clk_control;
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign in_TREADY_V = ap_phi_mux_storemerge_phi_fu_196_p6;

assign in_TVALID_V_read_read_fu_116_p2 = in_TVALID_V;

assign internal_rst_done_V = 1'd0;

assign out_TDATA_V = call_ret_Deparser_fu_228_ap_return;

assign out_TKEEP_V = in_TKEEP_V;

assign out_TLAST_V = in_TLAST_V;

assign out_TREADY_V_read_read_fu_173_p2 = out_TREADY_V;

assign tuple_out_digest_data_DATA_V = 256'd0;

assign tuple_out_digest_data_VALID_V = 1'd1;

assign tuple_out_sume_metadata_DATA_V = StgValue_57_Pipeline_fu_208_out_sume_metadata_V;

assign tuple_out_sume_metadata_VALID_V = StgValue_57_Pipeline_fu_208_out_sume_metadata_vl;

endmodule //SimpleSumeSwitchCpp
